// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRPgwC09NGBUn6aggslmuiSa5IJuCMlZg',
    appId: '1:1090542554035:web:c13f4828bbef89b4b099c6',
    messagingSenderId: '1090542554035',
    projectId: 'signova-18ec8',
    authDomain: 'signova-18ec8.firebaseapp.com',
    databaseURL: 'https://signova-18ec8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'signova-18ec8.firebasestorage.app',
    measurementId: 'G-3S99QGVWBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHiQJgWCnMirBHC8lZASvILTnZA7JOHN0',
    appId: '1:1090542554035:android:16f3cebc71a07f02b099c6',
    messagingSenderId: '1090542554035',
    projectId: 'signova-18ec8',
    databaseURL: 'https://signova-18ec8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'signova-18ec8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcOHo6OrYCiYSRf-gg87zakhI4lWch1YM',
    appId: '1:1090542554035:ios:089ba264382282dbb099c6',
    messagingSenderId: '1090542554035',
    projectId: 'signova-18ec8',
    databaseURL: 'https://signova-18ec8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'signova-18ec8.firebasestorage.app',
    androidClientId: '1090542554035-93tfktmh06li4gr45fckfpp3pf4d0dkf.apps.googleusercontent.com',
    iosClientId: '1090542554035-8q7qc52gbfjperqfp5gbu3r6idk9pj0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.signova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcOHo6OrYCiYSRf-gg87zakhI4lWch1YM',
    appId: '1:1090542554035:ios:089ba264382282dbb099c6',
    messagingSenderId: '1090542554035',
    projectId: 'signova-18ec8',
    databaseURL: 'https://signova-18ec8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'signova-18ec8.firebasestorage.app',
    androidClientId: '1090542554035-93tfktmh06li4gr45fckfpp3pf4d0dkf.apps.googleusercontent.com',
    iosClientId: '1090542554035-8q7qc52gbfjperqfp5gbu3r6idk9pj0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.signova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRPgwC09NGBUn6aggslmuiSa5IJuCMlZg',
    appId: '1:1090542554035:web:6327f91c0417130fb099c6',
    messagingSenderId: '1090542554035',
    projectId: 'signova-18ec8',
    authDomain: 'signova-18ec8.firebaseapp.com',
    databaseURL: 'https://signova-18ec8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'signova-18ec8.firebasestorage.app',
    measurementId: 'G-D7KWMP53M3',
  );
}
